# Generated by Django 2.1.3 on 2018-12-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0026_auto_20181214_2144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_platform', models.BooleanField(db_index=True)),
                ('to_platform', models.BooleanField(db_index=True)),
                ('kind', models.CharField(choices=[('AS', 'Author Subscription'), ('NS', 'Newspaper Subscription'), ('DO', 'Donation'), ('FC', 'Free Credit'), ('PF', 'Platform fee')], db_index=True, max_length=2)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Credits')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_newspaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='articles.Newspaper')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_newspaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='articles.Newspaper')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
