# Generated by Django 2.1.3 on 2019-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_free_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Credits'),
        ),
    ]
