# Generated by Django 2.0 on 2017-12-27 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('picture', 'Picture')], default='newspaper', max_length=60)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('title', models.CharField(max_length=160)),
                ('perex', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='posts',
            field=models.ManyToManyField(to='articles.Post'),
        ),
        migrations.AddField(
            model_name='edition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to=settings.AUTH_USER_MODEL),
        ),
    ]
