server {
        listen       0.0.0.0:8000;
        listen       [::]:8000;
        server_name  cdn.kairly.com;

        location /static/ {
            alias /srv/app/static/;
        }
        location /media/ {
            alias /srv/app/media/;
        }
}

server {
        listen       0.0.0.0:8000 default_server;
        listen       [::]:8000 default_server;
        server_name  _;

        location / {
                proxy_pass         http://127.0.0.1:8080/;
                proxy_redirect     default;
                proxy_set_header   X-Real-IP  $remote_addr;
                proxy_set_header   Host       $host;
        }

        location /static/ {
                alias /srv/app/static/;
        }
        location /media/ {
                alias /srv/app/media/;
        }
}
