# Generated by Django 2.0.6 on 2018-06-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_localimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture_url',
        ),
    ]
