# Generated by Django 2.0.6 on 2018-06-29 08:42

from django.db import migrations


def forwards_func(apps, schema_editor):
    TwitterChannel = apps.get_model("sources", "TwitterChannel")

    for ch in TwitterChannel.objects.filter(enabled=True):
        ch.author.twitter_account = ch.twitter_account
        ch.author.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_twitter'),
        ('sources', '0002_auto_20180622_1759'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
