# Generated by Django 2.0.6 on 2018-08-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_ordered_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
    ]
