# Generated by Django 2.0.6 on 2018-08-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_category_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryuser',
            options={'ordering': ('ordering',)},
        ),
    ]
