# Generated by Django 2.0.6 on 2018-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_categoryuser_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryuser',
            name='ordering',
            field=models.IntegerField(default=999, verbose_name='Ordering'),
        ),
    ]
