# Generated by Django 2.1.3 on 2018-11-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180929_1834'),
        ('articles', '0019_auto_20181113_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryuser',
            name='topic',
        ),
    ]
