# Generated by Django 2.1.3 on 2018-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_categoryuser_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('medium', 'Medium')], default='personal', max_length=60),
        ),
    ]
