# Generated by Django 2.1.3 on 2018-12-14 21:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Subscription price'),
        ),
    ]
