# Generated by Django 2.1.3 on 2018-12-14 21:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subscription price'),
        ),
    ]
