# Generated by Django 2.1.3 on 2018-12-16 20:17

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("users", "User")
    Transaction = apps.get_model("credits", "Transaction")

    transactions = [
        Transaction(
            from_platform=True,
            to_user=user,
            kind='FC',  # free credit
            credits=350,
        )
        for user in User.objects.filter(is_active=True)
    ]
    Transaction.objects.bulk_create(transactions)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20181216_2016'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
