# Generated by Django 2.0 on 2018-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('rss', models.CharField(max_length=250)),
                ('parsing_rules', models.TextField(help_text='YAML with title, perex and content keys')),
            ],
        ),
    ]
