# Generated by Django 2.0 on 2018-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='provider_id',
            field=models.CharField(default='', help_text='Channel identifier', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
