# Generated by Django 2.0.6 on 2018-06-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20180622_1759'),
        ('users', '0007_import_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterchannel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='twitterchannel',
            name='topic',
        ),
        migrations.DeleteModel(
            name='TwitterChannel',
        ),
    ]
