# Generated by Django 2.0 on 2018-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_channel_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='provider_prefix',
            field=models.CharField(default='', help_text='Source identifier (namespace for guid)', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
