# Generated by Django 2.0.6 on 2018-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20180629_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parser',
            field=models.TextField(help_text='Parse rules to get content from webpage/rss.'),
        ),
    ]
