# Generated by Django 2.0 on 2018-03-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20180328_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='provider_prefix',
            new_name='provider',
        ),
    ]
