# Generated by Django 2.0.6 on 2018-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20180715_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Force User-Agent header when fetching RSS or post', max_length=250, null=True),
        ),
    ]
