# Generated by Django 2.0 on 2018-03-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_post_guid'),
        ('sources', '0004_auto_20180328_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Author'),
        ),
    ]
