# Generated by Django 2.0 on 2018-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_channel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parsing_rules',
            field=models.TextField(help_text='YAML with perex and content keys'),
        ),
    ]
