# Generated by Django 2.0 on 2018-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20180328_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parsing_rules',
            field=models.TextField(blank=True, help_text='YAML with perex and content keys'),
        ),
    ]
