# Generated by Django 2.0.7 on 2018-08-26 21:16

from django.db import migrations


def forwards_func(apps, schema_editor):
    Channel = apps.get_model("sources", "Channel")
    Post = apps.get_model("articles", "Post")

    # using simple hack, ignore topic becase current prod db
    # should have protected all topics or none for each user
    updated_authors = set()

    for ch in Channel.objects.all().select_related('author'):
        if not ch.parse_content_from_rss:
            continue

        ch.protected = False
        ch.save()

        if ch.author.id in updated_authors:
            continue

        updated_authors.add(ch.author.id)
        Post.objects.filter(author_id=ch.author.id).update(protected=False)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_channel_protected'),
        ('articles', '0009_post_protected'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
