# Generated by Django 2.0 on 2018-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_auto_20180328_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='parse_content_from_rss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parsing_rules',
            field=models.TextField(help_text='YAML with perex and content keys'),
        ),
    ]
