# Generated by Django 2.1.3 on 2018-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_protected_data'),
        ('articles', '0016_celiaxmoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='newspaper',
            field=models.CharField(blank=True, db_index=True, help_text="Automatically add to newspaper's backlog", max_length=160, null=True),
        ),
    ]
