# Generated by Django 2.1.3 on 2018-11-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_channel_newspaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='topic',
        ),
    ]
