# Generated by Django 2.0.3 on 2018-05-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20180328_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='parser',
            field=models.TextField(blank=True, help_text='Parse rules to get content from webpage.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Author'),
        ),
    ]
