# Generated by Django 2.1.3 on 2018-11-18 18:52

from django.db import migrations, connection

from collections import namedtuple


def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    for row in cursor.fetchall():
        yield nt_result(*row)


query = """
SELECT
    post_id,
    newspaper_id,
    GROUP_CONCAT(i.number) issue_numbers,
    GROUP_CONCAT(i.id) issue_ids,
    COUNT(*) cnt
FROM
    articles_issuepost ip JOIN
    articles_issue i ON (i.id = ip.issue_id)
GROUP BY i.newspaper_id, ip.post_id
HAVING cnt > 1
"""


def forwards_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(query)
        for row in namedtuplefetchall(cursor):
            numbers = row.issue_number
            issue_ids = row.issue_ids
            if isinstance(numbers, bytes):
                numbers = numbers.decode()
            if isinstance(issue_ids, bytes):
                issue_ids = issue_ids.decode()
            numbers = map(int, numbers.split(','))
            issue_ids = map(int, issue_ids.split(','))
            issues = list(zip(numbers, issue_ids))
            issues.sort(key=lambda t: t[0])
            for _, issue_id in issues[1:]:
                cursor.execute("DELETE FROM articles_issuepost WHERE issue_id = %s AND post_id = %s", [issue_id, row.post_id])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_remove_channel_topic'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
