# Generated by Django 2.0.3 on 2018-05-04 13:53
import yaml

from django.db import migrations


def forward(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Channel = apps.get_model('sources', 'Channel')
    for ch in Channel.objects.all():
        rules = yaml.load(ch.parsing_rules)
        content = rules['content']

        if content != '*':
            value = []
            for selectors in rules['perex'], content:
                if not isinstance(selectors, list):
                    selectors = [selectors]
                for selector in selectors:
                    elem = None
                    if isinstance(selector, dict):
                        elem = list(selector.keys())[0]
                        selector = list(selector.values())[0]

                    value.append(selector)
                    if elem:
                        value.append('  as: ' + elem)
                    value.append('')

            ch.parser = '\n'.join(value)
            ch.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20180504_1352'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
