# Generated by Django 2.0.3 on 2018-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_parser_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='skip_rules',
            field=models.TextField(blank=True, help_text='YAML'),
        ),
    ]
