# Generated by Django 2.1.3 on 2018-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_dedupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='skip_rules',
            new_name='directives',
        ),
    ]
