# Generated by Django 2.0.3 on 2018-05-04 14:52
import yaml
from django.db import migrations


def forward(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Channel = apps.get_model('sources', 'Channel')
    for ch in Channel.objects.all():
        rules = yaml.load(ch.parsing_rules)
        skip = rules.get('skip')

        if skip:
            domain = skip.get('domain')
            if domain:
                ch.skip_rules = 'domain: ' + domain
                ch.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_channel_skip_rules'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
