# Generated by Django 2.0.3 on 2018-05-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_skip_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='parsing_rules',
        ),
    ]
