# Generated by Django 2.0.3 on 2018-05-13 18:43

from django.db import migrations

AKTUALNE = """.perex

.clanek-telo p

.obrazek-ve-clanku img[0]
  move-after: .perex
"""

IDNES = """.opener
  tag: p

#content .bbtext
  p, h3

.opener-foto img

br
  tag: none
"""


def forward(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Channel = apps.get_model('sources', 'Channel')
    for ch in Channel.objects.all():
        if ch.provider.startswith('aktualne'):
            ch.parser = AKTUALNE
            ch.save()

        elif ch.provider.startswith('indes'):
            ch.parser = IDNES
            ch.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_remove_channel_parsing_rules'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
