# Generated by Django 2.0.5 on 2018-06-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_update_aktualne_subscription'),
        ('sources', '0014_newrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Save first with author to select a topic here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic'),
        ),
    ]
