# Generated by Django 2.0.5 on 2018-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_channle_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('name',)},
        ),
    ]
