# Generated by Django 2.0.5 on 2018-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_channel_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='provider',
            field=models.CharField(help_text='Source identifier (namespace for guid)', max_length=32),
        ),
    ]
