# Generated by Django 2.0.5 on 2018-06-01 11:11

from django.db import migrations


def forwards_func(apps, schema_editor):
    Channel = apps.get_model("sources", "Channel")
    Author = apps.get_model("articles", "Author")
    Topic = apps.get_model("articles", "Topic")

    aktualne = Author.objects.get(slug='aktualnecz')

    slugs = [
        ('aktualnecz-domaci', 'domaci'),
        ('aktualnecz-ekonomika', 'ekonomika'),
        ('aktualnecz-finance', 'ekonomika'),
        ('aktualnecz-kultura', 'kultura'),
        ('aktualnecz-nazory', 'nazory-komentare'),
        ('aktualnecz-sport', 'sport'),
        ('aktualnecz-zahranicni', 'zahranicni'),
    ]
    for provider, tslug in slugs:
        topic = Topic.objects.get(slug=tslug)
        channel = Channel.objects.get(provider=provider)

        channel.topic = topic
        channel.provider = 'aktualne'
        channel.author = aktualne
        channel.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_auto_20180601_1111'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
