# Generated by Django 2.0.6 on 2018-06-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_drop_aktualnecz_topic_authors'),
        ('sources', '0018_channel_topic_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twtter_account', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Author')),
                ('topic', models.ForeignKey(blank=True, help_text='Save first with author to select a topic here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic')),
            ],
        ),
    ]
