# Generated by Django 2.0.6 on 2018-06-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_twitterchannel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterchannel',
            old_name='twtter_account',
            new_name='twitter_account',
        ),
    ]
