# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test_py:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: v1-pydeps-{{ checksum "kairly-server/requirements.txt" }}

      - run: # install and activate virtual environment with pip
          command: |
            cd kairly-server
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache: # special step to save dependency cache
          key: v1-pydeps-{{ checksum "kairly-server/requirements.txt" }}
          paths:
            - "kairly-server/venv"

      - run: # run tests
          command: |
            cd kairly-server
            . venv/bin/activate
            pytest

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.10.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "47:93:33:75:8e:e3:c0:42:3f:2d:9c:2e:6d:0d:b4:43"

      - run: ssh-keyscan -H -p 14076 node-13.rosti.cz >> ~/.ssh/known_hosts
      - run: ssh-keyscan -H -p 14930 node-13.rosti.cz >> ~/.ssh/known_hosts
      - run: ssh-keyscan -H -p 15218 node-14.rosti.cz >> ~/.ssh/known_hosts

      - run: sudo apt update && sudo apt install -y python3 python3-pip
      - run: sudo pip3 install invoke polib

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "client/package.json" }}

      - run:
          command: |
            cd client
            npm install

      - save_cache:
          paths:
            - client/node_modules
          key: v4-dependencies-{{ checksum "client/package.json" }}

      - run: invoke deploy
      - run: invoke deploy.cron


workflows:
  version: 2

  test_py:
    jobs:
      - test_py

  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: production
            branches:
              ignore: /.*/
