# Generated by Django 2.0.6 on 2018-06-26 11:09
import requests

from django.db import migrations

from django.core.files import File
from django.core.files.temp import NamedTemporaryFile


def forwards_func(apps, schema_editor):
    pass
    """
    Migtations is no longer valid

    User = apps.get_model("users", "User")
    for user in User.objects.filter(picture__isnull=True):
        if not user.picture_url:
            continue
        resp = requests.get(user.picture_url)
        if resp.status_code == requests.codes.ok:
            if resp.headers['Content-Type'] == 'image/jpeg':
                img_suffix = 'jpg'
            elif resp.headers['Content-Type'] == 'image/png':
                img_suffix = 'png'
            elif resp.headers['Content-Type'] == 'image/gif':
                img_suffix = 'gif'
            else:
                image_type = user.picture_url.split('?')[0].split('.')[-1]
                img_suffix = {'jpeg': 'jpg'}.get(image_type, image_type)

            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(resp.content)
            img_temp.flush()

            fname = "{}.{}".format(user.username, img_suffix)
            user.picture.save(fname, File(img_temp), save=True)
            user.save()
    """


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0003_user_picture'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
