# Generated by Django 2.0.6 on 2018-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_account',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
