# Generated by Django 2.0.6 on 2018-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180715_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('explore_tab', models.CharField(max_length=160, verbose_name='Explore Tab')),
                ('ordering', models.IntegerField(verbose_name='Ordering')),
            ],
        ),
    ]
