# Generated by Django 2.0.6 on 2018-07-21 12:36

from django.db import migrations


def forwards_func(apps, schema_editor):
    Category = apps.get_model("users", "Category")
    Category.objects.create(name='Recommended', explore_tab='Best of Kairly', ordering=1)
    Category.objects.create(name='News', explore_tab='Politics', ordering=1)
    Category.objects.create(name='Politics', explore_tab='Politics', ordering=2)
    Category.objects.create(name='Journalists & Commentators', explore_tab='Politics', ordering=3)
    Category.objects.create(name='Think-thanks', explore_tab='Politics', ordering=4)
    Category.objects.create(name='Sport News', explore_tab='Sport', ordering=1)
    Category.objects.create(name='Athletes', explore_tab='Sport', ordering=2)
    Category.objects.create(name='Sport Journalists', explore_tab='Sport', ordering=3)
    Category.objects.create(name='Sport Clubs', explore_tab='Sport', ordering=4)
    Category.objects.create(name='Tech News', explore_tab='Technology', ordering=1)
    Category.objects.create(name='Web Technologies', explore_tab='Technology', ordering=2)
    Category.objects.create(name='Product Design', explore_tab='Technology', ordering=3)
    Category.objects.create(name='Cryptocurrencies', explore_tab='Technology', ordering=4)
    Category.objects.create(name='Tech Companies', explore_tab='Technology', ordering=5)
    Category.objects.create(name='Science', explore_tab='Technology', ordering=6)
    Category.objects.create(name='Recipes', explore_tab='Lifestyle', ordering=1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_categories'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
