# Generated by Django 2.0.6 on 2018-07-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_categories_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('explore_tab', 'ordering')},
        ),
    ]
