# Generated by Django 2.0.6 on 2018-07-21 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180721_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('explore_tab', 'ordering'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
