# Generated by Django 2.0.6 on 2018-08-09 19:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    Category = apps.get_model("users", "Category")
    CategoryUser = apps.get_model("users", "CategoryUser")

    for category in Category.objects.all():
        for i, user in enumerate(category.users.all().order_by('username'), start=1):
            print("Adding {} into {}".format(user.username, category.name))
            CategoryUser.objects.create(category=category, user=user, ordering=i * 10)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_ordered_category'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
