# Generated by Django 2.0.6 on 2018-08-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_post_attachments'),
        ('users', '0016_auto_20180809_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryuser',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic'),
        ),
    ]
