# Generated by Django 2.0.6 on 2018-09-29 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180904_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='activity_history_start',
            field=models.DateField(default=datetime.date(2018, 9, 29)),
            preserve_default=False,
        ),
    ]
