# Generated by Django 2.0.6 on 2018-09-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180929_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_history',
            field=models.BigIntegerField(default=0),
        ),
    ]
