# Generated by Django 2.0.6 on 2018-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180929_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_history_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
