# Generated by Django 2.1.3 on 2019-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190227_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('medium', 'Medium'), ('medium', 'Feed')], default='personal', max_length=60),
        ),
    ]
