# Generated by Django 2.1.3 on 2019-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190513_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('medium', 'Medium'), ('feed', 'Feed')], default='personal', max_length=60),
        ),
    ]
