# Generated by Django 2.2.1 on 2019-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190524_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=190, null=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='YAML', verbose_name='Authors and Newspapers')),
            ],
        ),
    ]
