# Generated by Django 2.2.1 on 2019-11-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_exploretimeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploretimeline',
            old_name='content',
            new_name='yaml_content',
        ),
    ]
