# Generated by Django 2.2.1 on 2019-11-15 08:15
import oyaml as yaml
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ExploreTimeline = apps.get_model("users", "ExploreTimeline")
    Category = apps.get_model("users", "Category")
    CategoryUser = apps.get_model("users", "CategoryUser")
    tabs = ['News', 'Politics', 'Sport', 'Technology', 'Life']

    for tab in tabs:
        slug = tab.lower()

        if slug == 'news' or slug == 'politics':
            newspapers = [
                'janmikula/malostranskenoviny',
                'farin/nej-novinari-na-twitteru',
                'rozhlas/zpravy-z-domova',
            ]
        elif slug == 'sport':
            newspapers = [
                'aktualnecz/sport',
                'rozhlas/sport'
            ]
        elif slug == 'technology':
            newspapers = [
                'janmikula/technologicky-denik',
                'janmikula/product-design-weekly',
                'farin/elektromobilita'
            ]
        elif slug == 'life':
            newspapers = [
                'janmikula/tydenik-skola-hrou',
                'janmikula/parodicky-denicek',
                'dvtv/dvtv-rozhovory-tydne'
            ]
        else:
            newspapers = []

        authors = []
        for cat in Category.objects.filter(explore_tab=tab).order_by('ordering'):
            cat_authors = []
            for cu in CategoryUser.objects.filter(category=cat).order_by('ordering').select_related('user'):
                cat_authors.append(cu.user.username)

            authors.append({
                'en': cat.name,
                'cs': cat.name,
                'authors': cat_authors
            })

        content = {}
        content['newspapers'] = newspapers
        content['authors'] = authors
        ExploreTimeline.objects.create(slug=slug, yaml_content=yaml.dump(content, default_flow_style=False))


def reverse_func(apps, schema_editor):
    ExploreTimeline = apps.get_model("users", "ExploreTimeline")
    ExploreTimeline.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20191115_0814'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
