# Generated by Django 2.2.1 on 2019-11-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_explore_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryUser',
        ),
    ]
