# Generated by Django 2.0 on 2017-12-30 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('picture', models.CharField(max_length=300, verbose_name='Picture')),
                ('medium', models.CharField(max_length=160, verbose_name='Medium')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('edition', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='articles.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('picture', 'Picture')], default='newspaper', max_length=60)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('read_time', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=160)),
                ('picture', models.CharField(max_length=300, verbose_name='Picture')),
                ('perex', models.TextField(blank=True, null=True, verbose_name='Perex')),
                ('content', models.TextField(verbose_name='Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Author')),
            ],
        ),
        migrations.CreateModel(
            name='UserEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='posts',
            field=models.ManyToManyField(blank=True, to='articles.Post'),
        ),
    ]
