# Generated by Django 2.0.6 on 2018-06-22 17:59

import articles.period
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='editions')),
                ('period', models.CharField(choices=[('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32)),
                ('period_time', models.TimeField(null=True)),
                ('period_dow', models.IntegerField(null=True)),
            ],
            bases=(models.Model, articles.period.PeriodMixin),
        ),
        migrations.CreateModel(
            name='EditionBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_stamp', models.DateTimeField(null=True, verbose_name='Time when marked to publish')),
            ],
        ),
        migrations.CreateModel(
            name='EditionIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='EditionIssuePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('picture', 'Picture')], default='newspaper', max_length=60)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('guid', models.CharField(max_length=255, null=True, unique=True, verbose_name='External ID')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link to original article')),
                ('title', models.CharField(max_length=160)),
                ('picture', models.CharField(blank=True, max_length=300, null=True, verbose_name='Picture')),
                ('perex', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Perex')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionToAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32)),
                ('period_time', models.TimeField(null=True)),
                ('period_dow', models.IntegerField(null=True)),
            ],
            bases=(models.Model, articles.period.PeriodMixin),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
    ]
