# Generated by Django 2.0 on 2018-01-26 22:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('medium', models.CharField(blank=True, max_length=160, verbose_name='Medium')),
                ('picture', models.CharField(max_length=300, verbose_name='Picture')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('edition', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='articles.Author')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='EditionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('picture', 'Picture')], default='newspaper', max_length=60)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
                ('title', models.CharField(max_length=160)),
                ('picture', models.CharField(blank=True, max_length=300, null=True, verbose_name='Picture')),
                ('perex', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Perex')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Author')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Author')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='editionpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
        migrations.AddField(
            model_name='edition',
            name='posts',
            field=models.ManyToManyField(blank=True, through='articles.EditionPost', to='articles.Post'),
        ),
        migrations.AddField(
            model_name='edition',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Subscription'),
        ),
    ]
