# Generated by Django 2.0 on 2018-01-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180128_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditionPost',
            new_name='EditionIssuePost',
        ),
    ]
