# Generated by Django 2.0.6 on 2018-06-26 08:32

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    for post in Post.objects.filter(kind='newspaper', perex=''):
        post.perex = post.content
        post.content = ''
        post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180622_1759'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
