# Generated by Django 2.0 on 2018-01-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180128_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Edition',
        ),
    ]
