# Generated by Django 2.0 on 2018-01-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180128_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription',
            new_name='edition',
        ),
        migrations.RemoveField(
            model_name='editionissue',
            name='edition',
        ),
    ]
