# Generated by Django 2.0 on 2017-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171231_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
