# Generated by Django 2.0.6 on 2018-08-02 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_backlog_ordering'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edition',
            new_name='Newspaper',
        ),
    ]
