# Generated by Django 2.0 on 2018-01-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180128_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editionissue',
            old_name='subscription',
            new_name='edition',
        ),
    ]
