# Generated by Django 2.0.6 on 2018-08-02 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20180802_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditionBacklog',
            new_name='Backlog',
        ),
        migrations.RenameModel(
            old_name='EditionIssuePost',
            new_name='IssuePost',
        ),
        migrations.RenameModel(
            old_name='EditionIssue',
            new_name='Issue',
        ),
    ]
