# Generated by Django 2.0 on 2018-01-02 09:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20171231_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='perex',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Perex'),
        ),
    ]
