# Generated by Django 2.0 on 2018-01-28 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_auto_20180128_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscription',
            new_name='Subscription',
        ),
    ]
