# Generated by Django 2.0 on 2018-01-13 17:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('articles', '0007_auto_20180102_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='author',
            name='medium',
            field=models.CharField(blank=True, max_length=160, verbose_name='Medium'),
        ),
    ]
