# Generated by Django 2.0.6 on 2018-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180802_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.TextField(null=True),
        ),
    ]
