# Generated by Django 2.0 on 2018-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180128_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='period',
            field=models.CharField(default='Daily', max_length=160),
            preserve_default=False,
        ),
    ]
