# Generated by Django 2.0.6 on 2018-09-04 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_post_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='published',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Published'),
        )
    ]
