# Generated by Django 2.0 on 2018-01-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180113_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelOptions(
            name='usertags',
            options={'verbose_name_plural': 'User Tags'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
    ]
