# Generated by Django 2.0 on 2018-01-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180128_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='image',
            field=models.ImageField(null=True, upload_to='editions'),
        ),
    ]
