# Generated by Django 2.0 on 2018-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_edition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='edition',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
