# Generated by Django 2.0 on 2018-01-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180113_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='posts',
            new_name='posts_old',
        ),
    ]
