# Generated by Django 2.0 on 2018-01-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180113_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='edition',
            name='posts_old',
            field=models.ManyToManyField(blank=True, related_name='_edition_posts_old_+', to='articles.Post'),
        ),
        migrations.AddField(
            model_name='editionpost',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition'),
        ),
        migrations.AddField(
            model_name='editionpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
        migrations.AddField(
            model_name='edition',
            name='posts',
            field=models.ManyToManyField(blank=True, through='articles.EditionPost', to='articles.Post'),
        ),
    ]
