# Generated by Django 2.0 on 2018-03-07 09:32

from django.db import migrations
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Author = apps.get_model("articles", "Author")
    Edition = apps.get_model("articles", "Edition")
    for author in Author.objects.all():
        author.slug = slugify(author.name.replace(' ', ''))
        author.save()
    for edition in Edition.objects.all():
        edition.slug = edition.editor.slug + '/' + slugify(edition.title.replace(' ', ''))
        edition.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
