# Generated by Django 2.0 on 2018-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_slug_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
