# Generated by Django 2.0 on 2018-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180115_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionpost',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
