# Generated by Django 2.0 on 2018-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180307_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='slug',
            field=models.SlugField(help_text='should be slugified editor/title, fill it manually now', unique=True, verbose_name='Slug'),
        ),
    ]
