# Generated by Django 2.0.6 on 2018-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_drop_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, max_length=190, verbose_name='Slug'),
        ),
    ]
