# Generated by Django 2.0 on 2018-01-15 16:15

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Edition = apps.get_model("articles", "Edition")
    EditionPost = apps.get_model("articles", "EditionPost")
    for edition in Edition.objects.all():
        for ordering, post in enumerate(edition.posts_old.all(), start=1):
            ep = EditionPost(edition=edition, post=post, ordering=ordering)
            ep.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180115_1610'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
