# Generated by Django 2.0 on 2018-01-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_postdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='posts_old',
        ),
    ]
