# Generated by Django 2.0 on 2018-03-07 10:02

from django.db import migrations
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Edition = apps.get_model("articles", "Edition")
    for edition in Edition.objects.all():
        edition.slug = slugify(edition.title.replace(' ', ''))
        edition.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180307_0937'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
