# Generated by Django 2.0.6 on 2018-10-08 19:55
import re
import hashlib
from django.db import migrations

from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for post in Post.objects.all():
        if post.slug:
            continue

        # pure heuristic
        slug_words = []
        for part in re.split(r'[\?\.|\-]', post.title):
            words = part.split()
            if not slug_words or len(slug_words) < 5:
                slug_words.extend(words)
        slug = slugify(' '.join(slug_words[:9])[:64])

        h = hashlib.sha1()
        h.update(bytes(post.id))
        h.update(post.title.encode())
        slug += '--' + h.hexdigest()[:9]

        post.slug = slug
        post.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0014_post_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
