# Generated by Django 2.1.3 on 2018-11-11 21:33

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("users", "User")
    Channel = apps.get_model("sources", "Channel")
    SubscriptionToAuthor = apps.get_model("articles", "SubscriptionToAuthor")
    Post = apps.get_model("articles", "Post")
    Topic = apps.get_model("articles", "Topic")

    celiaxmoni = User.objects.get(username='celiaxmoni')

    Channel.objects.filter(author=celiaxmoni).update(topic=None)

    for s in SubscriptionToAuthor.objects.filter(author__username='celiaxmoni', topic__isnull=False):
        full_exists = SubscriptionToAuthor.objects.filter(user=s.user, author__username='celiaxmoni', topic__isnull=True).count()
        if full_exists:
            s.delete()
        else:
            s.topic = None
            s.save()

    for p in Post.objects.filter(topics__author=celiaxmoni):
        p.topics.clear()

    Topic.objects.filter(author=celiaxmoni).delete()


def reverse_func(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_post-slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
