# Generated by Django 2.0 on 2018-03-18 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0015_slug_value2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionToAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='edition',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('slug', 'editor')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together={('user', 'author')},
        ),
    ]
