# Generated by Django 2.0 on 2018-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20180318_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guid',
            field=models.DateTimeField(null=True, verbose_name='External ID'),
        ),
    ]
