# Generated by Django 2.0 on 2018-01-26 21:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Author = apps.get_model("articles", "Author")
    editor = Author.objects.get(name='Jan Mikula')
    Subscription = apps.get_model("articles", "Subscription")
    Subscription.objects.create(
        title='Prezidentské volby',
        description='Nejdůležitější informace z probíhajících prezidentských voleb.',
        editor=editor,
    )
    Subscription.objects.create(
        title='Olympijský zápisník',
        description='Aktuality z olympijského dění.',
        editor=editor,
    )
    Subscription.objects.create(
        title='Bits on the Block',
        description='Your shortcut to the crypto world.',
        editor=editor,
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_subscription_usersubscription'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
