# Generated by Django 2.0 on 2018-01-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Subscription'),
        ),
    ]
