# Generated by Django 2.1.3 on 2018-11-13 20:06
import pytz
from datetime import timedelta
from collections import namedtuple
from more_itertools import windowed

from django.db import migrations
from django.utils.timezone import now as timezone_now

Periodicity = namedtuple('Periodicity', ['frequency', 'time', 'dow'])
PeriodInterval = namedtuple('PeriodInterval', ['start', 'end', 'title'])


def forwards_func(apps, schema_editor):
    Topic = apps.get_model("articles", "Topic")
    Channel = apps.get_model("sources", "Channel")
    Newspaper = apps.get_model("articles", "Newspaper")
    Issue = apps.get_model("articles", "Issue")
    Post = apps.get_model("articles", "Post")
    IssuePost = apps.get_model("articles", "IssuePost")
    Backlog = apps.get_model("articles", "Backlog")

    for topic in Topic.objects.all():  # iterate over topic, they are unique. Channels can be linked to same newspaper.
        channel = Channel.objects.filter(topic=topic)[0]

        print("Creating issues for " + channel.newspaper)

        username, slug = channel.newspaper.split('/')
        newspaper = Newspaper.objects.get(slug=slug, editor__username=username)

        editor_tz = pytz.timezone(newspaper.editor.timezone)

        curr = None
        posts = []
        no = 1

        for post in Post.objects.filter(topics=channel.topic).order_by('published'):
            post_interval = get_period_interval(newspaper, post.published, editor_tz)
            if curr and curr.start != post_interval.start:
                issue = Issue.objects.create(
                    number=no,
                    published=curr.end,
                    editor=newspaper.editor,
                    newspaper=newspaper
                )
                for i, post in enumerate(posts):
                    IssuePost.objects.create(issue=issue, post=post, ordering=i)

                # print("Issues {}: {} {}".format(no, curr.start, curr.end))
                # print(">> {}".format(', '.join(str(post) for post in posts)))
                no += 1
                posts = []

            curr = post_interval
            posts.append(post)

        if posts:
            if curr and curr.end < timezone_now():
                issue = Issue.objects.create(
                    number=no,
                    published=curr.end,
                    editor=newspaper.editor,
                    newspaper=newspaper
                )
                for i, post in enumerate(posts):
                    IssuePost.objects.create(issue=issue, post=post, ordering=i)
            else:
                for i, post in enumerate(posts):
                    Backlog.objects.create(
                        newspaper=newspaper,
                        post=post,
                        publish_stamp=curr.end,
                        ordering=i
                    )


def reverse_func(apps, schema_editor):
    Topic = apps.get_model("articles", "Topic")
    Channel = apps.get_model("sources", "Channel")
    Newspaper = apps.get_model("articles", "Newspaper")
    Issue = apps.get_model("articles", "Issue")
    Backlog = apps.get_model("articles", "Backlog")

    for topic in Topic.objects.all():
        channel = Channel.objects.filter(topic=topic)[0]
        username, slug = channel.newspaper.split('/')
        newspaper = Newspaper.objects.get(slug=slug, editor__username=username)
        Issue.objects.filter(newspaper=newspaper).delete()
        Backlog.objects.filter(newspaper=newspaper).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_autonewspapers'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]


def get_period_interval(obj, dt, tzinfo):
    dt = dt.astimezone(tzinfo)
    interval = _get_period_interval_notz(obj, dt)

    # Fix DST shift, perid must be 1 hour longer or shorter when includes DST shift
    start = interval.start.astimezone(tzinfo)
    if start.hour != interval.start.hour:
        start += timedelta(hours=interval.start.hour - start.hour)
        interval = PeriodInterval(start, interval.end, interval.title)

    end = interval.end.astimezone(tzinfo)
    if end.hour != interval.end.hour:
        end += timedelta(hours=interval.end.hour - end.hour)
        interval = PeriodInterval(interval.start, end, interval.title)

    return interval


def _get_period_interval_notz(obj, dt):
    """Construct time interval which includes given datetime and matches
    current periodicity.
    """
    if obj.period in ['3x_per_day', '6x_per_day']:
        if obj.period == '3x_per_day':
            hours = [6, 12, 18]
            title = '3× per day'
        else:
            hours = [6, 9, 12, 15, 18, 21]
            title = '6× per day'

        if dt.hour < hours[0]:
            return PeriodInterval(
                dt.replace(hour=hours[-1], minute=0, second=0, microsecond=0) - timedelta(days=1),
                dt.replace(hour=hours[0], minute=0, second=0, microsecond=0),
                title
            )

        for h1, h2 in windowed(hours, 2):
            if dt.hour >= h1 and dt.hour < h2:
                return PeriodInterval(
                    dt.replace(hour=h1, minute=0, second=0, microsecond=0),
                    dt.replace(hour=h2, minute=0, second=0, microsecond=0),
                    title
                )

        return PeriodInterval(
            dt.replace(hour=hours[-1], minute=0, second=0, microsecond=0),
            dt.replace(hour=hours[0], minute=0, second=0, microsecond=0) + timedelta(days=1),
            title
        )

    elif obj.period == 'daily':
        sub_time = obj.period_time
        start = dt.replace(hour=sub_time.hour, minute=sub_time.minute, second=0, microsecond=0)
        if start > dt:
            start -= timedelta(days=1)
        return PeriodInterval(start, start + timedelta(days=1), 'Daily summary')

    elif obj.period == 'weekly':
        sub_time = obj.period_time
        start = dt.replace(hour=sub_time.hour, minute=sub_time.minute, second=0, microsecond=0)
        if start > dt:
            start -= timedelta(days=1)
        while start.isoweekday() != obj.period_dow:
            start -= timedelta(days=1)
        return PeriodInterval(start, start + timedelta(days=7), 'Weekly summary')

    else:
        raise ValueError()
