# Generated by Django 2.0 on 2018-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_post_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(max_length=300, null=True, verbose_name='Link to original article'),
        ),
        migrations.AlterField(
            model_name='post',
            name='guid',
            field=models.DateTimeField(null=True, unique=True, verbose_name='External ID'),
        ),
    ]
