# Generated by Django 2.0 on 2018-01-26 21:46

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Edition = apps.get_model("articles", "Edition")
    Subscription = apps.get_model("articles", "Subscription")

    volby = Subscription.objects.get(title='Prezidentské volby')
    olymp = Subscription.objects.get(title='Olympijský zápisník')

    for edition in Edition.objects.all():
        if edition.title.startswith('Prezidentské volby'):
            edition.subscription = volby
            edition.save()
        if edition.title.startswith('Olympijský deníček'):
            edition.subscription = olymp
            edition.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_edition_subscription'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
