# Generated by Django 2.1.3 on 2018-11-13 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0018_makeissues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together={('user', 'author')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='subscriptiontoauthor',
            name='topic',
        )
    ]
