# Generated by Django 2.0 on 2018-03-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_post_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='guid',
        ),
    ]
