# Generated by Django 2.0 on 2018-01-26 21:50

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_model("auth", "User")
    Subscription = apps.get_model("articles", "Subscription")
    UserSubscription = apps.get_model("articles", "UserSubscription")

    volby = Subscription.objects.get(title='Prezidentské volby')
    olymp = Subscription.objects.get(title='Olympijský zápisník')

    for user in User.objects.all():
        UserSubscription.objects.create(user=user, subscription=volby)
        UserSubscription.objects.create(user=user, subscription=olymp)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_edition_subscription'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
