# Generated by Django 2.0 on 2018-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_remove_post_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guid',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='External ID'),
        ),
    ]
