# Generated by Django 2.1.3 on 2018-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20181113_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='period_dow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='period_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
