# Generated by Django 2.0 on 2018-01-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertags',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='usertags',
            name='user',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='tags',
        ),
        migrations.DeleteModel(
            name='UserTags',
        ),
    ]
