# Generated by Django 2.1.3 on 2018-11-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20181116_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='period',
            field=models.CharField(choices=[('6x_per_day', '6x per day'), ('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('picture', 'Picture')], db_index=True, default='newspaper', max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Link to original article'),
        ),
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='period',
            field=models.CharField(choices=[('6x_per_day', '6x per day'), ('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32),
        ),
    ]
