# Generated by Django 2.0.3 on 2018-05-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20180328_1832'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE articles_post CHANGE content content longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
                'ALTER TABLE articles_post CHANGE perex perex longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
                'OPTIMIZE TABLE articles_post'
            ],
            reverse_sql=[]
        )
    ]
