# Generated by Django 2.0.3 on 2018-05-21 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_utf8mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
