# Generated by Django 2.1.3 on 2018-12-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20181130_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together=set(),
        ),
    ]
