# Generated by Django 2.0.5 on 2018-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_subscriptiontoauthor_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontoauthor',
            old_name='time',
            new_name='period_time',
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='period',
            field=models.CharField(choices=[('3X', '3x per day'), ('D', 'Daily'), ('W', 'Weekly')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='period_dow',
            field=models.IntegerField(null=True),
        ),
    ]
