# Generated by Django 2.1.3 on 2018-12-14 21:30
from decimal import Decimal
from django.db import migrations


def forwards_func(apps, schema_editor):
    Newspaper = apps.get_model("articles", "Newspaper")
    Newspaper.objects.all().update(price=Decimal(25))
    Newspaper.objects.filter(editor__username='idnescz').update(price=Decimal(0))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20181214_2129'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
