# Generated by Django 2.1.3 on 2018-12-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20181217_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_md5',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Source MD5'),
        ),
    ]
