# Generated by Django 2.0.5 on 2018-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20180523_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='period_time',
            field=models.TimeField(null=True),
        ),
    ]
