# Generated by Django 2.1.3 on 2018-12-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20181214_2144'),
        ('articles', '0024_auto_20181217_0904'),
    ]

    operations = [
    ]
