# Generated by Django 2.0.5 on 2018-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20180523_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='period',
            field=models.CharField(choices=[('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32),
        ),
    ]
