# Generated by Django 2.0.5 on 2018-05-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20180528_1126'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "UPDATE articles_subscriptiontoauthor SET period = '3x_per_day' WHERE period = '3X'",
                "UPDATE articles_subscriptiontoauthor SET period = 'daily' WHERE period = 'D'",
                "UPDATE articles_subscriptiontoauthor SET period = 'weekly' WHERE period = 'W'",
            ],
            reverse_sql=[
                "UPDATE articles_subscriptiontoauthor SET period = '3X' WHERE period = '3x_per_day'",
                "UPDATE articles_subscriptiontoauthor SET period = 'D' WHERE period = 'daily'",
                "UPDATE articles_subscriptiontoauthor SET period = 'W' WHERE period = 'weekly'",
            ]
        )
    ]
