# Generated by Django 2.0.5 on 2018-06-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_period_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Author')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('slug', 'author')},
        ),
    ]
