# Generated by Django 2.1.3 on 2018-12-26 20:35
import rapidjson as json
import hashlib

from django.db import migrations

from utils.url import clean_url


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for p in Post.objects.filter(attachments__isnull=False, kind='tweet'):
        attachments = json.loads(p.attachments)
        dirty = False
        for i, item in enumerate(attachments):
            try:
                href = item['href']
                href = clean_url(href)
                md5 = hashlib.md5(href.encode()).hexdigest()

                target = None
                for tp in Post.objects.filter(source_md5=md5).order_by('-published'):
                    if tp.source == href:
                        target = tp
                        break

                if target is not None:
                    item['source_href'] = item['href']
                    item['href'] = '/' + target.author.username + '/' + target.slug
                    dirty = True
            except KeyError:
                pass

        if dirty:
            p.attachments = json.dumps(attachments)
            p.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20181226_2034'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
