# Generated by Django 2.0.5 on 2018-06-01 09:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    Author = apps.get_model("articles", "Author")
    Topic = apps.get_model("articles", "Topic")

    aktualne = Author.objects.get(slug='aktualnecz')
    Topic.objects.create(name='domácí', slug='domaci', author=aktualne)
    Topic.objects.create(name='ekonomika', slug='ekonomika', author=aktualne)
    Topic.objects.create(name='kultura', slug='kultura', author=aktualne)
    Topic.objects.create(name='názory a komentáře', slug='nazory-komentare', author=aktualne)
    Topic.objects.create(name='sport', slug='sport', author=aktualne)
    Topic.objects.create(name='zahraniční', slug='zahranicni', author=aktualne)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20180601_0906'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
