# Generated by Django 2.1.3 on 2018-12-29 21:26

from django.db import migrations
from decimal import Decimal


def forwards_func(apps, schema_editor):
    free_authors = [
        'aktualnecz',
        'andrejbabis',
        'ct24',
        'ctk',
        'ctsport',
        'gabrielakoukalova',
        'hlidacipes',
        'hospodarskenoviny',
        'idnescz',
        'jiridrahos',
        'jiriovcacek',
        'jiripehe',
        'karelschwarzenberg',
        'marekhilser',
        'michalblaha',
        'michalhoracek',
        'mirektopolanek',
        'miroslavkalousek',
        'nigelfarage',
        'novakdjokovic',
        'parlamentnilisty',
        'petrakvitova',
        'petrcech',
        'petrfiala',
        'robertzaruba',
        'rogerfederer',
        'slush',
        'vaclavklaus',
        'zizala'
    ]

    User = apps.get_model("users", "User")
    User.objects.filter(is_active=False).exclude(username__in=free_authors).update(price=Decimal(25))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_merge_20181227_0935'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
