# Generated by Django 2.0.5 on 2018-06-01 10:23

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    Author = apps.get_model("articles", "Author")
    Topic = apps.get_model("articles", "Topic")

    aktualne = Author.objects.get(slug='aktualnecz')
    slugs = [
        ('aktualnecz-domaci', 'domaci'),
        ('aktualnecz-ekonomika', 'ekonomika'),
        ('aktualnecz-kultura', 'kultura'),
        ('aktualnecz-nazory-komentare', 'nazory-komentare'),
        ('aktualnecz-sport', 'sport'),
        ('aktualnecz-zahranicni', 'zahranicni'),
    ]
    for aslug, tslug in slugs:
        author = Author.objects.get(slug=aslug)
        topic = Topic.objects.get(slug=tslug)
        print("Processing {}".format(aslug))

        for post in Post.objects.filter(author=author).order_by('published'):
            try:
                matched = Post.objects.get(title=post.title, published=post.published, author=aktualne)
                matched.topics.add(topic)
                post.delete()
            except Post.DoesNotExist:
                post.topics.add(topic)
                post.author = aktualne
                post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20180601_0913'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
