# Generated by Django 2.1.3 on 2018-12-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_auto_20181229_2205'),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE
              articles_post p
            JOIN
              users_user u on (p.author_id = u.id)
            SET
              p.author_price = u.price
            WHERE
              p.draft = 0""",
        )
    ]
