# Generated by Django 2.0.5 on 2018-06-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_assign_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Topic'),
        ),
    ]
