# Generated by Django 2.1.3 on 2018-12-30 21:34

from django.db import migrations

from articles.weight import calculate_post_weight


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    post_exists = True
    while post_exists:
        # split migtation into chunks to save memory (production env is limited)
        post_exists = False
        print("Processing post batch (10000 posts)...")
        for post in Post.objects.filter(draft=False, weight__isnull=True)[:10000]:
            post_exists = True
            post.weight = calculate_post_weight(post)
            post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0033_freeze_author_price'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
