# Generated by Django 2.0.5 on 2018-06-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_subscriptiontoauthor_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together=set(),
        ),
    ]
