# Generated by Django 2.1.3 on 2019-01-30 20:42

from django.db import migrations, connection


def forwards_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('SELECT group_concat(id), user_id, author_id FROM articles_subscriptiontoauthor WHERE renewal = 1 GROUP BY user_id, author_id HAVING count(*) > 1')
        for row in cursor.fetchall():
            ids = row[0] if isinstance(row[0], str) else row[0].decode()
            for id in ids.split(',')[:-1]:
                cursor.execute(f'DELETE FROM articles_subscriptiontoauthor WHERE id = {id}')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_calculate_weight'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
