# Generated by Django 2.0.5 on 2018-06-01 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0034_auto_20180601_1047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together={('user', 'author', 'topic')},
        ),
    ]
