# Generated by Django 2.0.5 on 2018-06-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_auto_20180601_1047'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE articles_subscriptiontoauthor DROP KEY articles_subscriptiontoauthor_user_id_author_id_8e040834_uniq'
            ],
            reverse_sql=[]
        )
    ]
