# Generated by Django 2.1.3 on 2019-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_fix_double_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='newsletter_subscription_url',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Mailchimp subscribe form URL'),
        ),
    ]
