# Generated by Django 2.0.5 on 2018-06-01 10:58

from django.db import migrations


def forwards_func(apps, schema_editor):
    SubscriptionToAuthor = apps.get_model("articles", "SubscriptionToAuthor")
    Author = apps.get_model("articles", "Author")
    Topic = apps.get_model("articles", "Topic")

    aktualne = Author.objects.get(slug='aktualnecz')
    slugs = [
        ('aktualnecz-domaci', 'domaci'),
        ('aktualnecz-ekonomika', 'ekonomika'),
        ('aktualnecz-kultura', 'kultura'),
        ('aktualnecz-nazory-komentare', 'nazory-komentare'),
        ('aktualnecz-sport', 'sport'),
        ('aktualnecz-zahranicni', 'zahranicni'),
    ]
    for aslug, tslug in slugs:
        author = Author.objects.get(slug=aslug)
        topic = Topic.objects.get(slug=tslug)

        for sta in SubscriptionToAuthor.objects.filter(author=author):
            print("Changing subscription to topic subscription for {}, {}".format(sta.user_id, aslug))
            sta.author = aktualne
            sta.topic = topic
            sta.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_drop_constaint_manually'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
