# Generated by Django 2.0.5 on 2018-06-02 18:45

from django.db import migrations


def forwards_func(apps, schema_editor):
    Author = apps.get_model("articles", "Author")

    slugs = [
        'aktualnecz-domaci',
        'aktualnecz-ekonomika',
        'aktualnecz-kultura',
        'aktualnecz-nazory-komentare',
        'aktualnecz-sport',
        'aktualnecz-zahranicni',
    ]
    for aslug in slugs:
        Author.objects.get(slug=aslug).delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_update_aktualne_subscription'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
