# Generated by Django 2.0.6 on 2018-06-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_drop_aktualnecz_topic_authors'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE articles_post CHANGE title title longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci',
                'OPTIMIZE TABLE articles_post'
            ],
            reverse_sql=[]
        )
    ]
