# Generated by Django 2.1.3 on 2019-03-02 11:22

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    Post.objects.filter(kind='tweet', id__lt=500).delete()
    Post.objects.filter(kind='picture').delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_auto_20190227_2137'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
