# Generated by Django 2.1.3 on 2019-03-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_auto_20190302_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Issue'),
        ),
        migrations.AddField(
            model_name='post',
            name='ref_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('recommendation', 'Recommendation')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
