# Generated by Django 2.0.6 on 2018-06-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_author_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='period',
        ),
    ]
