# Generated by Django 2.0.6 on 2018-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_remove_edition_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='period',
            field=models.CharField(choices=[('3x_per_day', '3x per day'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32),
        ),
        migrations.AddField(
            model_name='edition',
            name='period_dow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='period_time',
            field=models.TimeField(null=True),
        ),
    ]
