# Generated by Django 2.1.3 on 2019-03-19 19:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_auto_20190303_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Article price'),
        ),
    ]
