# Generated by Django 2.0.6 on 2018-06-15 10:04
import datetime

from django.db import migrations


def forwards_func(apps, schema_editor):
    Edition = apps.get_model("articles", "Edition")

    for e in Edition.objects.all():
        e.period_time = datetime.time(9, 0)
        e.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_auto_20180615_1003'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
