# Generated by Django 2.1.3 on 2019-03-19 19:54

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    Post.objects.all().update(price=None)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_article_price'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
