# Generated by Django 2.0.6 on 2018-06-15 11:06

from django.db import migrations


def forwards_func(apps, schema_editor):
    EditionIssue = apps.get_model("articles", "EditionIssue")

    for ei in EditionIssue.objects.filter(edition__isnull=True):
        ei.delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_dailyvalue'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
