# Generated by Django 2.1.3 on 2019-03-19 21:15
from decimal import Decimal
from datetime import timedelta
from django.db.models import Sum

from django.db import migrations
from django.utils.timezone import now as timezone_now


def round_fair_price(price):
    if price < 0.1:
        return Decimal('0.1')
    if price < 1:
        return price.quantize(Decimal('0.1'))
    if price < 5:
        # round to 0.5
        return (price * 2).quantize(Decimal(0)) / 2
    return price.quantize(Decimal(0))


def calculate_weight(Post, author):
    query = Post.objects.filter(author=author, draft=False).exclude(kind='recommendation')
    count = query.count()

    if count == 0:
        return None, None, None

    # migration speed up, too much articles adter 2019 trim
    if count >= 1000:
        return None, Decimal('0.1'), None

    agg = query.aggregate(weight=Sum('weight'))
    weight = agg['weight']

    days = (timezone_now() - query.order_by('published').first().published).days

    return Decimal(weight), None, days  # norm to one month


def forwards_func(apps, schema_editor):
    print()  # print endline
    Post = apps.get_model("articles", "Post")
    User = apps.get_model("users", "User")
    for author in User.objects.filter(price__gt=0):
        print(f"Processing {author.username}...")
        query = Post.objects.filter(author=author, draft=False).exclude(kind='recommendation')

        weight, price, days = calculate_weight(Post, author)
        if weight is None:
            if price is None:
                price = round_fair_price(author.price / 5)
            query.update(price=price)

        else:
            total_price = days / Decimal(30) * author.price
            for post_id, post_weight in query.values_list('id', 'weight'):
                weight_fraction = post_weight / weight
                price = min(Decimal(author.price) / 2, Decimal(weight_fraction) * total_price)
                price = round_fair_price(price)
                Post.objects.filter(id=post_id).update(price=price)

    Post.objects.filter(draft=False, price__isnull=True).exclude(kind='recommendation').update(price=0)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0043_reset_reused_field'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
