# Generated by Django 2.0.6 on 2018-06-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0044_drop_standalone_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionissue',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition'),
        ),
    ]
