# Generated by Django 2.0.6 on 2018-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_auto_20180615_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editionissue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='editionissue',
            name='title',
        ),
        migrations.AddField(
            model_name='editionissue',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
