# Generated by Django 2.0.6 on 2018-06-15 11:13
from collections import defaultdict

from django.db import migrations


def forwards_func(apps, schema_editor):
    EditionIssue = apps.get_model("articles", "EditionIssue")
    n = defaultdict(lambda: 1)

    for ei in EditionIssue.objects.order_by('published'):
        ei.number = n[ei.edition_id]
        n[ei.edition_id] += 1
        ei.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0046_auto_20180615_1113'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
