# Generated by Django 2.0.6 on 2018-06-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_fill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(verbose_name='Ready to publish')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition')),
            ],
        ),
    ]
