# Generated by Django 2.0.6 on 2018-06-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0048_editionbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionbacklog',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
            preserve_default=False,
        ),
    ]
