# Generated by Django 2.0.6 on 2018-06-19 09:38

from django.db import migrations


def forwards_func(apps, schema_editor):
    Author = apps.get_model("articles", "Author")

    for author in Author.objects.all():
        users = list(author.users.all())
        if users:
            author.user = users[0]
            author.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_auto_20180619_0937'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
