# Generated by Django 2.0.6 on 2018-06-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0051_user_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='users',
        ),
    ]
