# Generated by Django 2.0.6 on 2018-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_auto_20180619_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editionbacklog',
            name='publish',
        ),
        migrations.AddField(
            model_name='editionbacklog',
            name='publish_stamp',
            field=models.DateTimeField(null=True, verbose_name='Time when marked to publish'),
        ),
    ]
