# Generated by Django 2.0.6 on 2018-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0054_auto_20180619_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='timezone',
            field=models.CharField(default='Europe/Prague', max_length=160, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
