# Generated by Django 2.0.6 on 2018-06-22 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Topic'),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='articles.Topic'),
        ),
        migrations.AddField(
            model_name='editionissuepost',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.EditionIssue'),
        ),
        migrations.AddField(
            model_name='editionissuepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
        migrations.AddField(
            model_name='editionissue',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition'),
        ),
        migrations.AddField(
            model_name='editionissue',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editionissue',
            name='posts',
            field=models.ManyToManyField(blank=True, through='articles.EditionIssuePost', to='articles.Post'),
        ),
        migrations.AddField(
            model_name='editionbacklog',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Edition'),
        ),
        migrations.AddField(
            model_name='editionbacklog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
        migrations.AddField(
            model_name='edition',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('slug', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontoauthor',
            unique_together={('user', 'author', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'edition')},
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('slug', 'editor')},
        ),
    ]
