# Generated by Django 2.0.7 on 2018-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_perex_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionbacklog',
            name='ordering',
            field=models.IntegerField(null=True),
        ),
    ]
