# Generated by Django 2.0.6 on 2018-08-02 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_auto_20180802_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='edition',
            new_name='newspaper',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='edition',
            new_name='newspaper',
        ),
        migrations.RenameField(
            model_name='issuepost',
            old_name='edition',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='edition',
            new_name='newspaper',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'newspaper')},
        ),
    ]
