# Generated by Django 2.0.6 on 2018-09-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180904_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
