# Generated by Django 2.0.6 on 2018-09-06 20:24
from dateutil.relativedelta import relativedelta

from django.db import migrations
from django.utils import timezone


def get_subscription_end(start):
    return start + relativedelta(months=1)


def forwards_func(apps, schema_editor):
    Subscription = apps.get_model("articles", "Subscription")
    SubscriptionToAuthor = apps.get_model("articles", "SubscriptionToAuthor")

    now = timezone.now()
    end = get_subscription_end(now)

    Subscription.objects.all().update(valid_from=now, valid_to=end)
    SubscriptionToAuthor.objects.all().update(valid_from=now, valid_to=end)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_subscription_validity'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
