# Generated by Django 2.0.6 on 2018-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_subscription_validity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
