# Generated by Django 2.1.3 on 2018-11-13 09:07
from datetime import time

from django.db import migrations
# from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    # User = apps.get_model("users", "User")
    Channel = apps.get_model("sources", "Channel")
    SubscriptionToAuthor = apps.get_model("articles", "SubscriptionToAuthor")
    Subscription = apps.get_model("articles", "Subscription")
    Newspaper = apps.get_model("articles", "Newspaper")
    # Post = apps.get_model("articles", "Post")
    Topic = apps.get_model("articles", "Topic")

    t21_00 = time(*map(int, "21:00".split(':', maxsplit=1)))
    t18_00 = time(*map(int, "18:00".split(':', maxsplit=1)))
    t15_00 = time(*map(int, "15:00".split(':', maxsplit=1)))
    t09_00 = time(*map(int, "9:00".split(':', maxsplit=1)))

    periods = {
        'aktualnecz/domaci': ('6x_per_day', None, None),
        'aktualnecz/zahranicni': ('6x_per_day', None, None),
        'aktualnecz/kultura': ('daily', t15_00, None),
        'aktualnecz/nazory-komentare': ('daily', t09_00, None),

        'idnescz/zpravy': ('6x_per_day', None, None),

        'rozhlas/zpravy-z-domova': ('6x_per_day', None, None),
        'rozhlas/zpravy-ze-sveta': ('6x_per_day', None, None),
        'rozhlas/ekonomika': ('daily', t18_00, None),
        'rozhlas/veda-technologie': ('daily', t15_00, None),
        'rozhlas/komentare': ('daily', t09_00, None),
        'rozhlas/zivotni-styl': ('daily', t18_00, None),
        'rozhlas/kultura': ('daily', t21_00, None),
    }

    for topic in Topic.objects.all():
        key = topic.author.username + '/' + topic.slug

        period, period_time, period_dow = periods.get(key, ('3x_per_day', None, None))

        newspaper = Newspaper.objects.create(
            title=topic.name[0].upper() + topic.name[1:],
            slug=topic.slug,
            description="",
            editor=topic.author,
            period=period,
            period_time=period_time,
            period_dow=period_dow,
        )

        Channel.objects.filter(topic=topic).update(newspaper=key)

        for sub in SubscriptionToAuthor.objects.filter(topic=topic):
            Subscription.objects.create(
                user=sub.user,
                newspaper=newspaper,
                valid_from=sub.valid_from,
                valid_to=sub.valid_to,
                renewal=sub.renewal
            )
            sub.delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_celiaxmoni'),
        ('sources', '0008_channel_newspaper'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
