# Generated by Django 2.1.3 on 2018-11-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20181113_2146'),
        ('users', '0022_remove_categoryuser_topic'),
        ('sources', '0009_remove_channel_topic')
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='topic',
        #     unique_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='topic',
        #     name='author',
        # ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
