# Generated by Django 2.1.3 on 2018-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20181116_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='editions'),
        ),
    ]
