# Generated by Django 2.1.3 on 2018-12-14 21:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20181130_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Donation'),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Donation'),
        ),
    ]
