# Generated by Django 2.1.3 on 2018-12-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_post_source_md5'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE articles_post SET source_md5 = MD5(source) WHERE source IS NOT NULL",
        )
    ]
