# Generated by Django 2.1.3 on 2018-12-26 18:30
import hashlib

from django.db import migrations

from utils.url import clean_url


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for p in Post.objects.filter(source__isnull=False, source__contains='?', kind='newspaper'):
        url = clean_url(p.source)
        if url != p.source:
            p.source = url
            p.source_md5 = hashlib.md5(url.encode()).hexdigest()
            p.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_md5_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
