# Generated by Django 2.1.3 on 2018-12-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_clean_source_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Source MD5'),
        ),
    ]
