# Generated by Django 2.1.3 on 2018-12-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_merge_20181219_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontoauthor',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
