# Generated by Django 2.1.3 on 2018-12-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20181219_0959'),
        ('articles', '0029_replace_links_in_tweets'),
    ]

    operations = [
    ]
