# Generated by Django 2.1.3 on 2018-12-29 22:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_set_author_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frozen author price at publish time'),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
