# Generated by Django 2.1.3 on 2019-02-27 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_newspaper_newsletter_subscription_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frozen author price at publish time'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='subscriptiontoauthor',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Donation'),
        ),
    ]
