# Generated by Django 2.1.3 on 2019-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0039_drop_legacy_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
