# Generated by Django 2.1.3 on 2019-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0044_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('recommendation', 'Recommendation'), ('link', 'Link')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
