# Generated by Django 2.1.3 on 2019-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_auto_20190402_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't show hidden posts in authors detail"),
        ),
    ]
