# Generated by Django 2.1.3 on 2019-05-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0046_post_hidden'),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE
              articles_post p
            SET
              p.hidden = 1
            WHERE
              p.kind = 'link'""",
        )
    ]
