# Generated by Django 2.2.1 on 2019-06-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0047_hidden_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Newspaper')),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='co_editors',
            field=models.ManyToManyField(related_name='_newspaper_co_editors_+', through='articles.CoEditor', to=settings.AUTH_USER_MODEL),
        ),
    ]
