# Generated by Django 2.2.1 on 2019-07-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0048_auto_20190609_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='backlog',
            name='editorial_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.EditorialComment'),
        ),
    ]
