# Generated by Django 2.2.1 on 2019-07-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0049_auto_20190709_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialcomment',
            name='position',
            field=models.CharField(default='right', max_length=32),
            preserve_default=False,
        ),
    ]
