# Generated by Django 2.2.1 on 2019-07-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_editorialcomment_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='editorial_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.EditorialComment'),
        ),
    ]
