# Generated by Django 2.2.1 on 2019-07-11 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0051_auto_20190709_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorialComment',
            new_name='Editorial',
        ),
    ]
