# Generated by Django 2.2.1 on 2019-07-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0052_auto_20190711_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='editorial_comment',
            new_name='editorial',
        ),
    ]
