# Generated by Django 2.2.1 on 2019-07-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_auto_20190711_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='kind',
            field=models.CharField(choices=[('article', 'Article'), ('tweets', 'Tweets')], default='article', max_length=60),
            preserve_default=False,
        ),
    ]
