# Generated by Django 2.2.1 on 2019-07-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0054_editorial_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(null=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Editorial')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post')),
            ],
        ),
    ]
