# Generated by Django 2.2.1 on 2019-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0055_editorialtweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='title',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
