# Generated by Django 2.2.1 on 2019-07-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0056_auto_20190711_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepost',
            name='editorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Editorial'),
        ),
    ]
