# Generated by Django 2.2.1 on 2019-08-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_issuepost_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='publish_in',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
    ]
