# Generated by Django 2.2.1 on 2019-08-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_backlog_publish_in'),
    ]

    operations = [
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE
              articles_backlog b
            SET
              b.publish_in = 1
            WHERE
              b.publish_stamp IS NOT NULL""",
        )
    ]
