# Generated by Django 2.2.1 on 2019-08-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0059_publish_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='publish_stamp',
        ),
    ]
