# Generated by Django 2.2.6 on 2019-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0060_remove_backlog_publish_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet'), ('recommendation', 'Recommendation'), ('link', 'Link'), ('video', 'Video')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
