# Generated by Django 3.0.2 on 2020-01-18 16:24

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for p in Post.objects.filter(attachments__startswith="b'", kind='tweet'):
        try:
            p.attachments = eval(p.attachments).decode('utf-8')
            p.save()
        except Exception:
            p.delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0061_auto_20191125_2029'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
