# Generated by Django 2.2.1 on 2020-01-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0063_fixjson'),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE articles_post MODIFY attachments LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;""",
        )
    ]
