# Generated by Django 3.0.2 on 2020-01-24 21:23

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    for p in Post.objects.raw("SELECT * FROM articles_post WHERE kind = 'newspaper' AND source like %s AND (content like %s or perex like %s)", ['http://%', '%src="//%', '%src="//%']):
        p.content = p.content.replace('src="//', 'src="http://').replace('href="//', 'href="http://')
        p.perex = p.perex.replace('src="//', 'src="http://').replace('href="//', 'href="http://')
        p.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0064_collate'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
