# Generated by Django 2.2.1 on 2020-02-02 09:06

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    for p in Post.objects.filter(kind='comment', draft=True):
        p.draft = False
        p.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0065_fill_protocol'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
