# Generated by Django 2.2.1 on 2020-02-05 14:36

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0066_comments_remove_draft_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='editions'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('comment', 'Comment'), ('tweet', 'Tweet'), ('recommendation', 'Recommendation'), ('link', 'Link'), ('video', 'Video')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
