# Generated by Django 2.2.1 on 2020-02-06 08:08

from django.db import migrations
from django.utils.timezone import now as timezone_now


def forwards_func(apps, schema_editor):
    IssuePost = apps.get_model("articles", "IssuePost")
    Editorial = apps.get_model("articles", "Editorial")
    Backlog = apps.get_model("articles", "Backlog")
    EditorialTweet = apps.get_model("articles", "EditorialTweet")
    Post = apps.get_model("articles", "Post")

    now = timezone_now()

    for editorial in Editorial.objects.filter(kind='article'):
        try:
            ip = IssuePost.objects.get(editorial=editorial)
            published = ip.issue.published
            author_id = ip.issue.editor_id
        except IssuePost.DoesNotExist:
            try:
                bl = Backlog.objects.get(editorial=editorial)
                published = now
                author_id = bl.newspaper.editor_id
            except Backlog.DoesNotExist:
                # print(f"unused editorial {editorial.title}")
                editorial.delete()
                continue

        post = Post.objects.create(
            kind='comment',
            published=published,
            title=editorial.title,
            content=editorial.content,
            draft=False,
            author_id=author_id,
            hidden=True
        )
        EditorialTweet.objects.create(editorial=editorial, post=post, ordering=9999)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0067_auto_20200205_1436'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
