# Generated by Django 2.2.1 on 2020-02-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0068_editoral_as_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='layout',
            field=models.TextField(null=True),
        ),
    ]
