# Generated by Django 2.2.1 on 2020-02-06 09:08
import orjson as json
from django.db import migrations

"""
Sample layout
[
    {post: 324},
    {post: 101},
    [
        'cols-2-1',
        [
            {post: 301}
        ],
        [
            'editorial',
            {post: 21},
            {post: 22}
        ]
    ],
    {type: 'header', title: 'Dalsi sekce'},
    ...
]
"""


def forwards_func(apps, schema_editor):
    Issue = apps.get_model("articles", "Issue")
    IssuePost = apps.get_model("articles", "IssuePost")
    EditorialTweet = apps.get_model("articles", "EditorialTweet")

    for issue in Issue.objects.all():
        layout = []
        query = IssuePost.objects.filter(issue=issue).select_related('editorial').order_by('ordering', '-post__published')
        for ip in query:
            post_data = {'post': ip.post_id}
            if not ip.editorial:
                layout.append(post_data)
                continue

            editorial = ip.editorial
            editorial_data = [
                'editorial',
            ]
            for post_id in EditorialTweet.objects.filter(editorial=editorial).order_by('ordering').values_list('post_id', flat=True):
                editorial_data.append({'post': post_id})
                IssuePost.objects.create(
                    issue=issue,
                    post_id=post_id,
                    ordering=9999  # temp value, will be dropped
                )

            if editorial.position == 'left':
                layout.append([
                    'cols-1-2',
                    editorial_data,
                    [post_data],
                ])
            else:
                layout.append([
                    'cols-2-1',
                    [post_data],
                    editorial_data,
                ])

        issue.layout = json.dumps(layout).decode()
        issue.save()


def reverse_func(apps, schema_editor):
    IssuePost = apps.get_model("articles", "IssuePost")
    IssuePost.objects.filter(ordering=9999).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0069_issue_layout'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
