# Generated by Django 3.0.2 on 2020-02-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0070_issue_layout_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='editorial',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Editorial'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='newspaper',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='articles.Newspaper'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='post',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='articles.Post'),
        ),
    ]
