# Generated by Django 3.0.2 on 2020-02-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0071_auto_20200207_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backlog',
            new_name='BacklogX',
        ),
    ]
