# Generated by Django 3.0.2 on 2020-02-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0072_auto_20200207_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('layout', models.TextField(null=True)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='BacklogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Backlog')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post')),
            ],
        ),
        migrations.AddField(
            model_name='backlog',
            name='posts',
            field=models.ManyToManyField(blank=True, through='articles.BacklogPost', to='articles.Post'),
        ),
    ]
