# Generated by Django 3.0.2 on 2020-02-07 20:31
import orjson as json
from django.db import migrations


def forwards_func(apps, schema_editor):
    Newspaper = apps.get_model("articles", "Newspaper")
    EditorialTweet = apps.get_model("articles", "EditorialTweet")
    BacklogX = apps.get_model("articles", "BacklogX")
    Backlog = apps.get_model("articles", "Backlog")
    BacklogPost = apps.get_model("articles", "BacklogPost")

    query = Newspaper.objects.filter(backlogx__publish_in__isnull=False).select_related('editor').distinct()
    for newspaper in query:
        issues = [(1, 'upcoming'), (2, 'next')]

        bp_bulk = []

        for num, backlog_name in issues:
            logs = list(BacklogX.objects.filter(newspaper=newspaper, publish_in=num).order_by('ordering', 'post__published').select_related('post'))
            if not logs:
                continue

            layout = []
            backlog = Backlog.objects.create(name=backlog_name, newspaper=newspaper)

            for ip in logs:
                post_data = {'post': ip.post_id}
                bp_bulk.append(BacklogPost(backlog=backlog, post_id=ip.post_id))

                if not ip.editorial:
                    layout.append(post_data)
                    continue

                editorial = ip.editorial
                editorial_data = [
                    'editorial',
                ]
                for post_id in EditorialTweet.objects.filter(editorial=editorial).order_by('ordering').values_list('post_id', flat=True):
                    editorial_data.append({'post': post_id})
                    bp_bulk.append(BacklogPost(backlog=backlog, post_id=post_id))

                if editorial.position == 'left':
                    layout.append([
                        'cols-1-2',
                        editorial_data,
                        [post_data],
                    ])
                else:
                    layout.append([
                        'cols-2-1',
                        [post_data],
                        editorial_data,
                    ])

            backlog.layout = json.dumps(layout).decode()
            backlog.save()

        if bp_bulk:
            BacklogPost.objects.bulk_create(bp_bulk)


def reverse_func(apps, schema_editor):
    BacklogPost = apps.get_model("articles", "BacklogPost")
    Backlog = apps.get_model("articles", "Backlog")
    BacklogPost.objects.all().delete()
    Backlog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0073_auto_20200207_2029'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
