# Generated by Django 3.0.2 on 2020-02-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0074_backlog_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuepost',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='issuepost',
            name='ordering',
        ),
    ]
