# Generated by Django 3.0.2 on 2020-02-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0075_auto_20200207_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backlogpost',
            unique_together={('backlog', 'post')},
        ),
    ]
