# Generated by Django 3.0.2 on 2020-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0076_auto_20200218_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='editorialtweet',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='editorialtweet',
            name='post',
        ),
        migrations.AlterField(
            model_name='backlog',
            name='layout',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BacklogX',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='EditorialTweet',
        ),
    ]
