# Generated by Django 2.2.1 on 2020-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0076_auto_20200218_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='layout',
            field=models.TextField(default='[]'),
        ),
    ]
