# Generated by Django 2.2.1 on 2020-01-28 09:51

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    Post.objects.filter(author__kind='feed', kind='recommendation', ref_post__isnull=False).update(kind='reference')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0077_auto_20200221_0731'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
