# Generated by Django 2.2.1 on 2020-02-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0077_auto_20200220_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='editorialtweet',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='editorialtweet',
            name='post',
        ),
        migrations.DeleteModel(
            name='BacklogX',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='EditorialTweet',
        ),
    ]
