# Generated by Django 3.0.2 on 2020-02-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0078_kind_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('newspaper', 'Newspaper'), ('comment', 'Comment'), ('tweet', 'Tweet'), ('recommendation', 'Recommendation'), ('reference', 'Reference'), ('link', 'Link'), ('video', 'Video')], db_index=True, default='newspaper', max_length=60),
        ),
    ]
