# Generated by Django 3.0.2 on 2020-02-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0079_auto_20200229_1211'),
    ]

    operations = [
        migrations.RunSQL(
            """DELETE p FROM
            articles_post p
            left outer join articles_backlogpost bp ON(bp.post_id=p.id)
            left outer join articles_issuepost ip ON(ip.post_id=p.id)
            where kind='comment' and (bp.id is null and ip.id is NULL)""",
        )
    ]
