# Generated by Django 3.0.2 on 2020-03-27 11:54
import html
from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")
    for post in Post.objects.filter(kind='link'):
        post.perex = '<p>' + html.escape(post.perex) + '</p>'
        post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0080_drop_unused_comments'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
