# Generated by Django 3.0.2 on 2020-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0081_link_rich_perex'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='last_issue',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
