# Generated by Django 3.0.2 on 2020-04-15 19:38

from django.db import migrations


def forwards_func(apps, schema_editor):
    Newspaper = apps.get_model("articles", "Newspaper")
    Issue = apps.get_model("articles", "Issue")
    for newspaper in Newspaper.objects.all():
        issue = Issue.objects.filter(newspaper=newspaper).order_by('-number').first()
        if issue:
            newspaper.last_issue = issue.number
            newspaper.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0082_newspaper_last_issue'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
