# Generated by Django 2.0.6 on 2018-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(help_text='Source identifier (namespace for guid)', max_length=32)),
                ('rss', models.CharField(max_length=250)),
                ('parse_content_from_rss', models.BooleanField(default=False)),
                ('parser', models.TextField(blank=True, help_text='Parse rules to get content from webpage.')),
                ('skip_rules', models.TextField(blank=True, help_text='YAML')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TwitterChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_account', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
