# Generated by Django 2.0.6 on 2018-06-22 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('articles', '0002_auto_20180622_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterchannel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twitterchannel',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Save first with author to select a topic here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic'),
        ),
        migrations.AddField(
            model_name='channel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Save first with author to select a topic here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Topic'),
        ),
    ]
