# Generated by Django 2.0.7 on 2018-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='protected',
            field=models.BooleanField(default=True, help_text='Only users logged in can see full content'),
        ),
    ]
