# Generated by Django 2.1.3 on 2018-12-05 20:27

from django.db import migrations


def forwards_func(apps, schema_editor):
    Channel = apps.get_model("sources", "Channel")

    Channel.objects.filter(directives='domain: video.aktualne.cz')\
        .update(directives='skip domain video.aktualne.cz')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_auto_20181205_1914'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
