# Generated by Django 2.1.3 on 2019-01-17 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sources.directives
import sources.parser.parser


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_calculate_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0012_directives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('newspaper', 'Newspaper'), ('tweet', 'Tweet')], max_length=60, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Automation')),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='directives',
            field=models.TextField(blank=True, validators=[sources.directives.validate_directives]),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parser',
            field=models.TextField(help_text='Parse rules to get content from webpage/rss.', validators=[sources.parser.parser.validate_rules]),
        ),
    ]
