# Generated by Django 2.1.3 on 2019-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20190117_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='import_links',
            field=models.BooleanField(default=False),
        ),
    ]
