# Generated by Django 2.1.3 on 2019-05-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_channel_import_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateRss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss', models.CharField(max_length=250)),
                ('channnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Channel')),
            ],
        ),
    ]
