# Generated by Django 2.2.1 on 2019-05-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_alternaterss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternaterss',
            old_name='channnel',
            new_name='channel',
        ),
    ]
