# Generated by Django 2.2.1 on 2019-07-25 09:39
import hashlib

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for post in Post.objects.filter(kind='tweet', source__contains='/None/').select_related('author'):
        if not post.author or not post.author.twitter_account or not post.source:
            continue

        post.source = post.source.replace('/None/', f'/{post.author.twitter_account}/')
        post.title = post.title.replace('None:', f'{post.author.twitter_account}:')
        post.source_md5 = hashlib.md5(post.source.encode()).hexdigest()
        post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_auto_20190524_0924'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
