# Generated by Django 2.2.1 on 2019-07-25 10:14

from django.db import migrations


def forwards_func(apps, schema_editor):
    Post = apps.get_model("articles", "Post")

    for post in Post.objects.filter(kind='tweet', content__contains='\n'):
        post.content = post.content.replace('\n', '<br/>')
        post.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_fix_none_in_url'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
