server {
        listen       0.0.0.0:8000;
        listen       [::]:8000;

        if ($http_host = www.kairly.com) {
                rewrite  (.*)  https://kairly.com$1;
        }

        # Don't redirect favicon.ico to nodejs. It returns 404 anyway
        # and adds too much noise into log
        location = /favicon.ico {
                return 404;
        }

        location /_nuxt/assets/ {
                alias /srv/app/assets;
        }

        location / {
                proxy_pass         http://127.0.0.1:3000/;
                proxy_redirect     default;
                proxy_set_header   X-Real-IP  $remote_addr;
                proxy_set_header   Host       $host;
        }

        location /api/ {
                proxy_pass         https://kairly-2648.rostiapp.cz/api/;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location /admin/ {
                proxy_pass         https://kairly-2648.rostiapp.cz/admin/;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location /static/ {
                proxy_pass         https://kairly-2648.rostiapp.cz/static/;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location /media/ {
                proxy_pass         https://kairly-2648.rostiapp.cz/media/;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location /sitemap.xml {
                proxy_pass         https://kairly-2648.rostiapp.cz/sitemap.xml;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location /robots.txt {
                proxy_pass         https://kairly-2648.rostiapp.cz/robots.txt;
                proxy_redirect     default;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        location  ~ ^/([^/]+)/([^/]+)/rss$ {
                # proxy_redirect is not allowed together with variables
                proxy_pass         https://kairly-2648.rostiapp.cz/$1/$2/rss;
                proxy_set_header   Host kairly-2648.rostiapp.cz;
        }

        #location /static/ {
        #        alias /srv/static/;
        #}
}
